#!/bin/bash
#SBATCH --job-name=${JOB_NAME}
#SBATCH --output=./log_files/${JOB_NAME}.out
#SBATCH --error=./log_files/${JOB_NAME}.err
#SBATCH --nodes=2
#SBATCH --time=00:30:00
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:4
#SBATCH --hint=nomultithread
#SBATCH --constraint=gpu
#SBATCH --partition=debug
#SBATCH --exclusive
source ~/.slurm_env
#SBATCH --account=$SLURM_ACCOUNT

# Source common environment files
source ~/.tests_runpath
cd "$TESTS_RUNPATH" || exit

# Set environment variables
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export NCCL_DEBUG=INFO
export NCCL_IB_HCA=ipogif0
export NCCL_IB_CUDA_SUPPORT=1

# Load required modules
source /opt/cray/pe/cpe/23.12/restore_lmod_system_defaults.sh
module load cray/23.12
source /opt/cray/pe/cpe/23.12/restore_lmod_system_defaults.sh
module load cray-python/3.11.5
source /opt/cray/pe/cpe/23.12/restore_lmod_system_defaults.sh

# Optionally source WandB environment
if [ "${USE_WANDB}" = "1" ]; then
    source ~/.wandb_env
    export WANDB_MODE=online
fi

# Execute the Python script
echo "Test started $(date)"
srun /opt/cray/pe/python/3.11.5/bin/python -u "${SCRIPT}"
echo "Test done $(date)"