#!/bin/bash
#SBATCH --job-name=${JOB_NAME}
#SBATCH --output=./log_files/${JOB_NAME}.out
#SBATCH --error=./log_files/${JOB_NAME}.err
#SBATCH --nodes=1
#SBATCH --time=00:30:00
#SBATCH --cpus-per-task=1
#SBATCH --ntasks-per-core=1

# NOTE: these two should match
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:2

#SBATCH --hint=nomultithread
#SBATCH --partition=multi_gpu
#SBATCH --exclusive

# Source common environment files
source ~/.tests_runpath
cd "$TESTS_RUNPATH" || exit

# Set environment variables
if [ -z "$SLURM_CPUS_PER_TASK" ]; then
    export OMP_NUM_THREADS=1
else
    export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
fi
export NCCL_DEBUG=INFO
export NCCL_IB_HCA=ipogif0
export NCCL_IB_CUDA_SUPPORT=1

# Optionally source WandB environment
if [ "${USE_WANDB}" = "1" ]; then
    source ~/.wandb_env
    export WANDB_MODE=online
fi

# Execute the Python script
echo "Test started $(date)"
export CUDA_VISIBLE_DEVICES=$(echo $SLURM_LOCALID)
export NCCL_P2P_DISABLE=0
export NCCL_SHM_DISABLE=0
export NCCL_IB_DISABLE=0

echo "Activating virtual environment ../myvenv"
source ../myvenv/bin/activate
echo "Python executable: $(which python3)"

srun --gpu-bind=map_gpu:${SLURM_LOCALID} python3 -u "${SCRIPT}"
echo "Test done $(date)"